models/Post.php
<?php

namespace app\models;

use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "posts".
 *
 * @property int $id
 * @property string $title
 * @property string $slug
 * @property string $content
 * @property integer $dateCreated
 * @property boolean $hidden
 * 
 * @property Tag[] $tags
 * @property string $preview
 */
class Post extends ActiveRecord
{

    const CUT = '<!--cut-->';

    /**
     * @var array|string
     */
    public $setTags = [];

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'posts';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'slug', 'content'], 'required'],
            [['content'], 'string'],
            [['dateCreated'], 'integer'],
            [['hidden'], 'boolean'],
            [['title', 'slug'], 'string', 'max' => 255],
            [['slug'], 'unique'],
            [['setTags'], 'safe'],
        ];
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'createdAtAttribute' => 'dateCreated',
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'slug' => 'Slug',
            'content' => 'Content',
            'dateCreated' => 'Date Created',
            'hidden' => 'Hidden',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        if (!$this->setTags) {
            $this->setTags = [];
        }
        $this->setTags = array_map('intval', $this->setTags);
        $savedTags = [];
        foreach ($this->tags as $tag) {
            if (in_array(intval($tag->id), $this->setTags)) {
                $savedTags[] = intval($tag->id);
            } else {
                $this->unlink('tags', $tag, true);
                $tag->calcRating();
            }
        }
        foreach ($this->setTags as $tagId) {
            if (!in_array($tagId, $savedTags)) {
                $tag = Tag::findOne($tagId);
                $this->link('tags', $tag);
                $tag->calcRating();
            }
        }
        
        return parent::afterSave($insert, $changedAttributes);
    }

    /**
     * @return \yii\db\ActiveQuery
     * @throws \yii\base\InvalidConfigException
     */
    public function getTags()
    {
        return $this->hasMany(Tag::class, ['id' => 'tagId'])
            ->viaTable('posts2tags', ['postId' => 'id'])
            ->orderBy(['name' => 'ASC']);
    }

    public static function findByTag(Tag $tag)
    {
        return self::find()
            ->leftJoin('posts2tags', '"posts2tags"."postId"="posts"."id"')
            ->leftJoin('tags', '"tags"."id"="posts2tags"."tagId"')
            ->where(['tags.id' => $tag->id]);
    }

    public function getPreview()
    {
        $cut_pos = strpos($this->content, self::CUT);
        if ($cut_pos !== false) {
            return substr($this->content, 0, $cut_pos);
        } else {
            return $this->content;
        }
    }
}

controllers/PostController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Post;
use app\models\PostSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends Controller
{

    public $layout = 'onecolumn';

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['index', 'create', 'update', 'delete'],
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Post models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Post model.
     * @param string $slug
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($slug)
    {
        $this->layout = 'main';
        return $this->render('view', [
            'model' => $this->findModel(['slug' => $slug]),
        ]);
    }

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Post();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'slug' => $model->slug]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'slug' => $model->slug]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/TagController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Tag;
use app\models\TagSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TagController implements the CRUD actions for Tag model.
 */
class TagController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['index', 'create', 'update', 'delete', 'view'],
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update', 'delete', 'view'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Tag models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TagSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Tag model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Tag model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Tag();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Tag model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Tag model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Tag model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Tag the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Tag::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/post/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\Select2;
use app\models\Tag;
use app\models\Post;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\Post */
/* @var $form yii\widgets\ActiveForm */

$model->setTags = ArrayHelper::getColumn($model->tags,'id');

?>

<div class="post-form">

    <pre>
        Examples:<br>
        <?= Html::encode('<div class="youtube-player" data-id="ZH4YSF-i5dY"></div>') ?><br>
        <?= Html::encode('<div class="youtube-player format4x3" data-id="-0k6_ePGYHQ"></div>') ?><br>
        <?= Html::encode(Post::CUT) ?>
    </pre>

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'slug')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'content')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'hidden')->checkbox() ?>

    <?= $form->field($model, 'dateCreated')->textInput() ?>

    <?= $form->field($model, 'setTags', ['template' => "{label} ".Html::a("[ Добавить тег ]", ['/tag/create'], ['class' => 'adminlink'])."\n{input}\n{hint}\n{error}"])->widget(Select2::classname(), [
            'language' => 'ru-RU',
            'data' => ArrayHelper::map(Tag::find()->orderBy(['name' => 'ASC'])->all(),'id','name'),
            'options' => ['multiple' => 'multiple'],
            'pluginOptions' => [
                'allowClear' => true,
                'buttonContainer'=>'<div class="form-group" style="position:relative;" />',
                'checkboxName' => 'Post[setTags]'
            ],
        ]);
    ?>
    
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Сохранить') ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/post/_preview.php
<?php

use app\helpers\DateHelper;
use app\widgets\TagsList;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $post app\models\Post */

$dateHuman = DateHelper::getTimeAgo($post->dateCreated);
$dateOnServer = DateHelper::dateInClientTimezone('d.m.Y H:i', $post->dateCreated);

?>
<article class="post">
    <h2 class="post-title">
        <?= Html::a($post->title, "/posts/{$post->slug}") ?>
    </h2>
    <div class="post-body">
        <?= $post->preview ?>
    </div>
    <div class="post-footer">
        <?= Html::a("<span class='date' data-timestamp='{$post->dateCreated}'>{$dateOnServer}</span> ({$dateHuman})", "/posts/{$post->slug}", ['class' => 'post-published']) ?>
        <?php if (!Yii::$app->user->isGuest): ?>
            <a class="adminlink" href="/post/update?id=<?=$post->id?>">[ EDIT ]</a>
        <?php endif ?>
        <?= TagsList::widget(['post' => $post]) ?>
    </div>
</article>

views/post/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = 'Создать пост';

?>
<div class="post-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/post/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\PostSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Posts';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Post', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [

            'id',
            'title',
            'slug',
//            'content:ntext',
//            'preview:ntext',
            'dateCreated',
            'hidden:boolean',

            [
                'format' => 'raw',
                'label' => 'Actions',
                'value' => function($model, $key, $index, $column) {
                    return Html::a('[Update]', ['update', 'id' => $model->id]) . ' ' .
                        Html::a('[Delete]', ['delete', 'id' => $model->id], [
                            'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                            'data-method' => 'post',
                        ]);
                }
            ],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

views/post/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = 'Редактировать пост: ' . $model->title;

?>
<div class="post-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/post/view.php
<?php

use app\helpers\DateHelper;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = Yii::$app->name . ' / ' . $model->title;
$this->registerMetaTag(['name' => 'description', 'content' => $model->preview], "description");

$dateHuman = DateHelper::getTimeAgo($model->dateCreated);
$dateOnServer = DateHelper::dateInClientTimezone('d.m.Y H:i', $model->dateCreated);

?>
<article class="post">
    <h2 class="post-title"><?= Html::encode($model->title) ?></h2>
    <div class="post-body">
        <?= $model->content ?>
    </div>
    <div class="post-footer">
        <span class="post-published">Published <span class="date" data-timestamp="<?=$model->dateCreated?>"><?= $dateOnServer ?></span> (<?= $dateHuman ?>)</span>
        <?php if (!Yii::$app->user->isGuest): ?>
            <a class="adminlink" href="/post/update?id=<?=$model->id?>">[ EDIT ]</a>
        <?php endif ?>
        <ul class="post-tags tagslist">
            <?php foreach ($model->tags as $tag): ?>
                <li>
                    <?= Html::a($tag->name, "/tags/{$tag->name}") ?>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
</article>